/**
 * Authentication service (PRD §2.3, §2.4).
 *
 * Pure, transport-agnostic helpers used by `routes/auth-routes.ts` to:
 *   - issue short-lived JWT access tokens signed with `JWT_SECRET`
 *   - verify an inbound access token and surface its `userId` claim
 *   - create, consume, and revoke opaque refresh tokens persisted in the
 *     `refresh_tokens` table
 *
 * Refresh tokens are random UUIDs generated by `node:crypto`'s `randomUUID()`.
 * They have no embedded metadata — all state (user binding, expiration) lives
 * in the database so revocation is a simple row delete.
 */
import { randomUUID } from 'node:crypto';
import jwt, { type SignOptions } from 'jsonwebtoken';
import { db } from '../lib/db.js';
import { ErrorCode, HttpError } from '../lib/http-error.js';

/** Access token TTL in seconds (PRD §2.3: 15 minutes). */
export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;

/** Refresh token TTL in milliseconds (PRD §2.4: 7 days). */
export const REFRESH_TOKEN_TTL_MS = 7 * 24 * 60 * 60 * 1000;

export interface AccessTokenPayload {
  userId: string;
}

function getJwtSecret(): string {
  const secret = process.env.JWT_SECRET;
  if (!secret || secret.length === 0) {
    throw new Error('JWT_SECRET is not set — refusing to issue or verify tokens.');
  }
  return secret;
}

/**
 * Sign and return a JWT carrying the given user id. Uses the default HS256
 * algorithm and a 15-minute `exp` claim.
 */
export function issueAccessToken(userId: string): string {
  const options: SignOptions = { expiresIn: ACCESS_TOKEN_TTL_SECONDS };
  return jwt.sign({ userId }, getJwtSecret(), options);
}

/**
 * Verify an inbound access token.
 *
 * @throws HttpError(401, 'UNAUTHORIZED') — signature invalid, token expired,
 *   or the payload is missing a string `userId` claim.
 */
export function verifyAccessToken(token: string): AccessTokenPayload {
  let decoded: unknown;
  try {
    decoded = jwt.verify(token, getJwtSecret());
  } catch (err) {
    if (err instanceof jwt.JsonWebTokenError) {
      throw new HttpError(401, ErrorCode.UNAUTHORIZED, 'Invalid or expired token.');
    }
    throw err;
  }

  if (
    !decoded ||
    typeof decoded !== 'object' ||
    !('userId' in decoded) ||
    typeof (decoded as { userId: unknown }).userId !== 'string'
  ) {
    throw new HttpError(401, ErrorCode.UNAUTHORIZED, 'Invalid token payload.');
  }

  return { userId: (decoded as { userId: string }).userId };
}

/**
 * Generate a new opaque refresh token, persist it bound to `userId` with a
 * 7-day expiry, and return the token string. The token is a `crypto.randomUUID()`
 * value — unguessable, single-purpose, server-side revocable.
 */
export async function createRefreshToken(userId: string): Promise<string> {
  const token = randomUUID();
  const expiresAt = new Date(Date.now() + REFRESH_TOKEN_TTL_MS);

  await db
    .insertInto('refresh_tokens')
    .values({ token, user_id: userId, expires_at: expiresAt })
    .execute();

  return token;
}

/**
 * Consume a refresh token exactly once. On success the row is deleted so the
 * token cannot be replayed — callers that need a fresh refresh token must
 * call `createRefreshToken` immediately after. This single-use semantic is
 * the server side of the rotate-on-use pattern required by PRD §8.2 / T-029.
 *
 * @throws HttpError(401, 'UNAUTHORIZED') — the token is unknown, expired, or
 *   has already been consumed.
 */
export async function consumeRefreshToken(token: string): Promise<string> {
  // `deleteFrom ... returning` is atomic: either we obtain the row AND delete
  // it, or we get nothing back. This guarantees that two concurrent callers
  // with the same token cannot both receive a userId.
  const deleted = await db
    .deleteFrom('refresh_tokens')
    .where('token', '=', token)
    .returning(['user_id', 'expires_at'])
    .executeTakeFirst();

  if (!deleted) {
    throw new HttpError(401, ErrorCode.UNAUTHORIZED, 'Invalid refresh token.');
  }

  if (new Date(deleted.expires_at).getTime() <= Date.now()) {
    // The row has already been removed above, so no further cleanup needed.
    throw new HttpError(401, ErrorCode.UNAUTHORIZED, 'Refresh token has expired.');
  }

  return deleted.user_id;
}

/**
 * Remove a refresh token from the database. Idempotent — no-op when the
 * token is unknown, so repeated logout requests still return a clean 200.
 */
export async function deleteRefreshToken(token: string): Promise<void> {
  await db.deleteFrom('refresh_tokens').where('token', '=', token).execute();
}

/**
 * If a user exists with the given identifier but registration was never
 * completed (no verified OTP was ever created for this identifier), delete
 * the stale row so re-registration can proceed. Otherwise throw.
 *
 * Users created outside the OTP flow (seed scripts, admin panel) have no
 * OTP history and are always considered fully registered.
 */
export async function guardIdentifier(value: string, field: 'phone' | 'email'): Promise<void> {
  const column = field === 'phone' ? 'phone' : 'email';
  const existing = await db
    .selectFrom('users')
    .where(column, '=', value)
    .select('id')
    .executeTakeFirst();
  if (!existing) return;

  const otpRecord = await db
    .selectFrom('otp_codes')
    .where('identifier', '=', value)
    .select('verified')
    .executeTakeFirst();

  // No OTP history → user was created outside the registration flow.
  // Verified OTP exists → user completed registration. Both are conflicts.
  if (!otpRecord || otpRecord.verified) {
    throw new HttpError(
      409,
      field === 'phone' ? ErrorCode.PHONE_ALREADY_REGISTERED : ErrorCode.EMAIL_ALREADY_REGISTERED,
      `${field === 'phone' ? 'Phone number' : 'Email address'} is already registered.`,
    );
  }

  // User has OTP attempts but never verified — stale row.
  await db.deleteFrom('users').where('id', '=', existing.id).execute();
}
